Import-Module posh-git
Import-Module oh-my-posh
# Aliases
# use single-quotes for strings with spaces
#Set-Alias -Name lsw -Value 'Get-ChildItem | Format-Wide' -Description 'ls but format-wide'
#Set-Alias list Get-ChildItemColorFormatWide
#Set-Theme ys
#Set-Theme pure
Set-Theme PowerlinePlus
#Set-Theme Powerlevel9k
# pshazz theme - auto-generated by pshazz
#try { $null = Get-Command pshazz -ea stop; pshazz init 'default' } catch { }


Set-Alias -Name np -Value C:\Windows\notepad.exe
set-alias -name rubyri -value C:\Ruby26-x64\bin\ri.cmd -Description "A workaround for ruby's ri, cuz in pwsh ri is remove-item"
Set-Alias -Name exp -Value explorer
Set-Alias -Name cygman -Value D:\Cygwin\bin\man.exe -Description "Show info file from cygwin which includes a lot more documentation than the windows emacs info"
Set-Alias -Name lsc -Value Get-ChildItemColorFormatWide -Description "Better alias for color ls"
Set-Alias -Name rdis -Value rdiscount -Description "Shorter rdiscount"
Set-Alias -Name pd -Value pandoc -Description "Shorter Pandoc"
Set-Alias -Name msys -Value D:\MSYS2\msys2_shell.cmd -Description "Use --help for invoke options"
Set-Alias -Name git-cola -Value C:\Users\Carl\AppData\Local\git-cola\bin\git-cola.exe -Description "Git-cola because "
Set-Alias -Name cygbash -Value D:\Cygwin\bin\bash.exe -Description "Use man tcsh for help"

## Functions

# Next is a function that allows me to change to my powershell directory where my profile is.
Function PSDir {Set-Location -Path D:\carl\documents\PowerShell\}
# This one sets an alias for the ri command in ruby

# This is just a function to cd to my notes dir
Function NotesDir {Set-Location -Path D:\Carl\Onedrive\Notable\Notes}
# Set-Alias to make notes dir even more easily accessible
Set-Alias -Name ndir -Value NotesDir
# Function for invoking wsl with carlc user and zsh shell
Function wslme {wsl -u carlc -e zsh}
Function gitdir {Set-Location -Path D:\Carl\Documents\GitHub}
Function gpgmee {gpg -se -r Carl}
Function localappdata {Set-Location -Path C:\Users\Carl\AppData}
Set-Alias -name localad -Value localappdata
Set-Alias -Name gitbash -Value 'D:\Program Files\Git\bin\bash.exe'
Set-Alias -Name ... -Value D:\Carl\Documents\PowerShell\Scripts\backwards_cd.ps1
Set-Alias -Name .. -Value D:\Carl\Documents\PowerShell\Scripts\backwards_cd1.ps1
Set-Alias -name ipinfo -Value .\getipinfo.ps1
