Import-Module posh-git
Import-Module oh-my-posh
# Aliases
# use single-quotes for strings with spaces
#Set-Alias -Name lsw -Value 'Get-ChildItem | Format-Wide' -Description 'ls but format-wide'
#Set-Alias list Get-ChildItemColorFormatWide
#Set-Theme ys
#Set-Theme pure
#Set-Theme PowerlinePlus
#Set-Theme Powerlevel9k
Set-Theme zash
# pshazz theme - auto-generated by pshazz
#try { $null = Get-Command pshazz -ea stop; pshazz init 'default' } catch { }


Set-Alias -Name np -Value C:\Windows\notepad.exe
# This one sets an alias for the ri command in ruby
set-alias -name rubyri -value D:\Ruby27-x64\bin\ri.cmd -Description "A workaround for ruby's ri, cuz in pwsh ri is remove-item"
Set-Alias -Name exp -Value explorer
Set-Alias -Name cygman -Value D:\Cygwin\bin\man.exe -Description "Show info file from cygwin which includes a lot more documentation than the windows emacs info"
Set-Alias -Name lsc -Value Get-ChildItemColorFormatWide -Description "Better alias for color ls"
Set-Alias -Name rdis -Value rdiscount -Description "Shorter rdiscount"
Set-Alias -Name pd -Value pandoc -Description "Shorter Pandoc"
Set-Alias -Name msys -Value D:\MSYS2\msys2_shell.cmd -Description "Use --help for invoke options"
Set-Alias -Name git-cola -Value C:\Users\Carl\AppData\Local\git-cola\bin\git-cola.exe -Description "Git-cola because "
Set-Alias -Name cygbash -Value D:\Cygwin\bin\bash.exe -Description "Use man tcsh for help"

## Functions

# Next is a function that allows me to change to my powershell directory where my profile is.
Function PSDir {Set-Location -Path D:\carl\documents\PowerShell\}

# This is just a function to cd to my notes dir
Function NotesDir {Set-Location -Path D:\Carl\Onedrive\Notable\Notes}
# Set-Alias to make notes dir even more easily accessible
Set-Alias -Name ndir -Value NotesDir
# Function for invoking ubuntu wsl with carlc user and zsh shell
Function wslme {wsl -d Ubuntu-20.04 -u carlc -e zsh}
# Function to get to standard parent git directory
Function gitdir {Set-Location -Path D:\Carl\Documents\GitHub}
# This is a function for git status, not Get-GitStatus, which is a posh-git cmdlet.
function gitst {git status}
Function gpgmee {gpg -se -r Carl}
Function localAppData {Set-Location -Path C:\Users\Carl\AppData}
Function globalAppData {Set-Location -Path D:\Carl\AppData}
Function npmDoc {Set-Location -Path 'C:\Program Files\nodejs\node_modules\npm\docs'}
# Backup folder for dotfiles in both Windows and Ubuntu
Function dotfiles_backup {Set-Location -Path D:\Carl\OneDrive\dotfiles_backup}
# Easily page thru long ls lists
Function lspage {ls | less}
# Easily open powershell profile in fvim
Function psprof {fvim D:\Carl\Documents\Powershell\Microsoft.Powershell_profile.ps1}
Set-Alias -Name dot_dir -Value dotfiles_backup
Set-Alias -name localad -Value localappdata
Set-Alias -Name gitbash -Value 'D:\Program Files\Git\bin\bash.exe'
Set-Alias -Name ... -Value D:\Carl\Documents\PowerShell\Scripts\backwards_cd.ps1
Set-Alias -Name .. -Value D:\Carl\Documents\PowerShell\Scripts\backwards_cd1.ps1
Set-Alias -name ipinfo -Value D:\Carl\Documents\PowerShell\Scripts\getipinfo.ps1
Set-alias -Name invo -Value Invoke-Item -description "Shorter invoke-item"
#node C:\Users\Carl\node_modules\which\bin\node-which
# Alias for Get-GitStatus function provided by posh-git
set-alias -Name gitstat -Value Get-GitStatus
Set-Alias -Name ls -Value Get-ChildItemColor
# Above makes the ls command always use Get-ChildItemColor
# This attaches the rename command to rename item
# ren is also an alias for rename-item
Set-Alias -Name rename -Value Rename-Item -Description "A smart rename alias"
